

[[constraint]]
  branch = "v0.1.0"
  name = "github.com/coolsnady/hcd"
  
[[constraint]]
  branch = "master"
  name = "github.com/coolsnady/hcrpcclient"

[[constraint]]
  branch = "master"
  name = "github.com/coolsnady/hcutil"